### PR TITLE
Fix for Issue 170

### LINKED ISSUE #170: Pinout diagram not rendering in t2 docs
Pin mapping diagram is not rendering in the Hardware API (below the pinout table):

screen shot 2017-08-08 at 11 12 57 am

(thanks for the bug report, @mittalshravika )

Debugging:

First check: did it deploy properly to Gitbook https://www.gitbook.com/book/tessel/t2-docs/activity (looks like yes)

2nd check: does it render in the markdown on Github?
https://github.com/tessel/t2-docs/blob/master/API/Hardware_API.md ugh no

3rd check: filepath says `Pin Mapping for Tessel`, so let’s look in the images folder

https://github.com/tessel/t2-docs/tree/master/images

it’s not there!

bug found: the image did not get committed to the folder

### PR DESCRIPTION
**Pull request by mittalshravika**
Fixes #170. The Pinout Diagram has been moved to the image folder and the relative path has also been added in the Hardware_API.md file.

### CODE REVIEW

**Comment by Frijol** [comment]
Something is odd here– the Files Changed tab is showing changes that don't make sense based on current master. For example, we already have relative linking in current master, but it's showing you deleting an absolute path from master to replace it with the relative link we already have.

Can you please try rebasing this branch on master (https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request)?

**Comment by mittalshravika** [comment]
Oh Okay. Should I remove this PR and start with a fresh one after rebasing the branch with the master?

**Comment by Frijol** [comment]
You should be able to push up the branch after the rebase and have this same PR still work. Might need to force-push though

**Comment by mittalshravika** [comment]
I was not able to rebase the branch issue-170 with tessel/master although I was able to rebase the master branch of 276linesofCode with tessel/master, so, I will create a new branch and work on that and close this PR.
Sorry for the inconvenience caused.

**Pull request closed without merging**
