### PR TITLE
adds link to __dirname docs

### PR DESCRIPTION
**Pull request by HipsterBrown**
Followup PR for https://github.com/tessel/t2-docs/pull/61#discussion_r61288659

### CODE REVIEW

**Comment by johnnyman727** [comment]
This looks good. I'm not sure if this would be the appropriate place, but it might be more satisfying for users to see an explanation of why they should use `__dirname` (because we're deploying to a different absolute location on Tessel than their host machine).

**Comment by HipsterBrown** [comment]
@johnnyman727 Yea, I'm not sure how much content is too much for certain sections of the docs.

**Comment by Frijol** [comment]
I think this is a good level of detail as it stands. It would be fun to do a "why it works the way it works" section of the docs or blog post somewhere, but the primary objective here is to make sure people get to "I know how to do this" as quickly as possible.

**Comment by Frijol** [comment]
ping!

**Pull request merged**
