### PR TITLE
Fixes #75; t2 ap --on/--off.

### LINKED ISSUE #75: t2 ap --trigger on/off => t2 ap --on/--off
Hello,

I thing docs need to update. I tried on/off commands as `t2 wifi`, and it works. But not at the `t2 ap`.

### PR DESCRIPTION
**Pull request by huseyinkozan**
Fixed.

Fixes #76 (edit by HipsterBrown to auto-close issue 75)

### CODE REVIEW

**Comment by HipsterBrown** [comment]
Thanks for fixing this @huseyinkozan. :clap: LGTM

**Comment by wyze** [comment]
LGTM. Have you signed [our CLA](http://www.dojofoundation.org/about/claForm) yet?

**Comment by huseyinkozan** [comment]
I thing I did it. How can I send the signed paper ? Is there an easy way ?

**Comment by huseyinkozan** [comment]
The CLA page gives me this error : 
```
The username or email address provided is already on file. Only one CLA needs to be filed per username/email address.
```
What should I do while sending pull requests ? Do I need to say "I signed the CLA" per request ?

**Comment by HipsterBrown** [comment]
No need to say you signed the CLA for each PR. If it says that you have signed already, then you're good to be merged. 👍

**Comment by wyze** [comment]
Nope, you don't need to send anything. Just confirm you signed it, and the above message does that. 😄

**Comment by HipsterBrown** [comment]
Weird that it closed the PR as well. But thanks again @huseyinkozan for contributing, we really appreciate it. :smile:

**Pull request merged**
