### PR TITLE
Update cli.md for npm install

### PR DESCRIPTION
**Pull request by Frijol**
@johnnyman727 r?

### CODE REVIEW

**Comment by johnnyman727** [comment]
I think we might want to note that you can install from npm to get the latest release but keep the cloning install instructions for people who want to be on the bleeding edge (we're not going to publish every time we merge a PR).

**Comment by Frijol** [comment]
Right, that's why this is on the docs page and the repo has different install instructions

**Comment by Frijol** [comment]
I'm assuming people who want the bleeding edge / are developing for CLI will go to the repo. Are you saying I should leave a note to link back to the repo?

**Comment by johnnyman727** [comment]
Oh you're totally right - I thought this was the CLI repo for some reason. Looks good!

**Pull request merged**
