### PR TITLE
added more explanation to I2C transfer command

### PR DESCRIPTION
**Pull request by Frijol**
r? @johnnyman727

### CODE REVIEW

**Comment by johnnyman727** [comment]
looks reasonable to me

**Comment by HipsterBrown** [comment]
@Frijol Do we have an entry in `GLOSSARY.md` for "register"? If not, that would be a nice addition with this PR.

**Comment by Frijol** [comment]
good idea, and as a bonus I added 'datasheet' too. Any further suggestions?

**Comment by HipsterBrown** [comment]
LGTM :+1: Thanks for working on this @Frijol! :clap:

**Pull request merged**
